### ISSUE TITLE
Identify necessary technical skills and major challenges

### ISSUE THREAD

**Issue by padma-g** [padma-g/info478-project#4]
What new technical skills will we need to learn in order to complete the project?

What major challenges do we anticipate?

**Comment by mygreattime** [comment]
The necessary technical skills that we need for this project include operating Shiny and r markdown. This also connects to the major challenges that we face because it may have been some time since we learned these skills in Info 201. Another challenge is that we may not be familiar with some population health topics so some extra research may be conducted.
